# Using the point_to_patch_weight.pkl file generated by the closest_point_to_patch.py function
# and the patch activation values from ICA-decomposed ECoG data from Julie, this script will
# calculate the activity of each point in the point cloud and then LeadField Matrix.
# The LeadField Matrix will be used to simulate the EEG data.

# %% initialize
import os
import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import mne


# %% load data
# load the point to patch weight
with open('point_to_patch_weight.pkl', 'rb') as f:
    point_to_patch_weight = pickle.load(f)

# load the patch activation values
ECoG = mne.io.read_raw_eeglab('CS_FullMotor500Hz_475.set')
ECoG_data = ECoG.get_data()
electrode_positions = ECoG.info.get_montage().get_positions()['ch_pos']
